// constants.ts
import type { Language } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', bcp47: 'en-US' },
  { code: 'hi', name: 'हिन्दी', bcp47: 'hi-IN' },
  { code: 'ml', name: 'മലയാളം', bcp47: 'ml-IN' },
  { code: 'te', name: 'తెలుగు', bcp47: 'te-IN' },
];

export const UI_STRINGS = {
  en: {
    selectLanguage: 'Select Your Language',
    appTitle: 'Krishi Mitra',
    welcomeMessage: 'Welcome! How can I help you today?',
    inputPlaceholder: 'Ask a question or describe the issue...',
    listening: 'Listening...',
    error: 'Sorry, something went wrong. Please check your connection and try again.',
    imageUpload: 'Image Uploaded',
    feedback: 'Was this helpful?',
    feedbackThanks: 'Thank you for your feedback!',
    header: {
      changeLanguage: 'Change language',
      logout: 'Logout',
      toggleVoiceOn: 'Enable voice',
      toggleVoiceOff: 'Disable voice',
      newChat: 'New chat',
      budgetPlanner: 'View budget planner',
      machinery: 'View agricultural machinery',
      cropInsurance: 'View crop insurance',
      weather: 'View weather reports',
      helpline: 'View helpline information',
      cropCalendar: 'View crop calendar',
      governmentSchemes: 'View government schemes',
      marketPrices: 'View market prices',
      alertPreferences: 'Alert Preferences',
    },
    auth: {
      login: 'Login',
      signup: 'Sign Up',
      username: 'Username',
      password: 'Password',
      welcomeBack: 'Welcome back!',
      createAccount: 'Create an account to save your history.',
      loginPrompt: 'Already have an account?',
      signupPrompt: 'Don\'t have an account?',
      userExists: 'This username is already taken.',
      userNotFound: 'Username not found.',
      invalidCredentials: 'Incorrect username or password.',
      genericError: 'An error occurred. Please try again.',
    },
    marketPrices: {
      title: 'Current Market Prices',
      selectRegion: 'Select Region',
      crop: 'Crop',
      price: 'Price (per Quintal)',
      trend: 'Trend',
      regions: {
        north: 'North',
        south: 'South',
        east: 'East',
        west: 'West',
      },
    },
    governmentSchemes: {
      title: 'Government Schemes',
      eligibility: 'Eligibility',
      benefits: 'Benefits',
      applicationProcess: 'How to Apply',
    },
    weatherAlerts: {
      title: 'Weather Alert',
      preferencesTitle: 'Alert Preferences',
      enableAlerts: 'Enable alerts for:',
      heavyRain: 'Heavy Rain',
      drought: 'Drought',
      frost: 'Frost',
    },
    cropCalendar: {
      title: 'Crop Calendar',
      selectCrop: 'Select a Crop',
      stage: 'Stage',
      timing: 'Timing / Month',
      filterBySeason: 'Filter by Season',
      all: 'All',
      kharif: 'Kharif',
      rabi: 'Rabi',
    },
    helpline: {
      title: 'Helpline Information',
      nationalHelplines: 'National Helplines',
      stateAuthorities: 'State Agricultural Authorities',
      nearbyOffices: 'Nearby Agricultural Offices',
      selectState: 'Select State',
      selectDistrict: 'Select District',
      region: 'Region',
      department: 'Department',
      contact: 'Contact',
    },
    machinery: {
      title: 'Agricultural Machinery',
      learnMore: 'Learn More',
      cost: 'Estimated Cost',
      subsidy: 'Government Subsidy',
    },
    cropInsurance: {
      title: 'Crop Insurance Schemes',
      coverage: 'Coverage',
      premium: 'Premium',
      eligibility: 'Eligibility',
      claimProcess: 'Claim Process',
      documentsRequired: 'Documents Required',
      keyBenefits: 'Key Benefits',
      visitWebsite: 'Visit Website',
    },
    weatherWidget: {
      title: 'Weather Forecast',
      searchPlaceholder: 'Enter city name...',
      cityNotFound: 'City not found. Please try another city.',
      serviceUnavailable: 'Weather service is currently unavailable.',
      fetchError: 'Failed to fetch weather data. Please check your connection.',
      tryAgain: 'Please try searching for another location.',
      feelsLike: 'Feels Like',
      humidity: 'Humidity',
      windSpeed: 'Wind',
      pressure: 'Pressure',
      visibility: 'Visibility',
      sunrise: 'Sunrise',
      sunset: 'Sunset',
    },
    weather: {
      title: 'Weather Reports',
      searchPlaceholder: 'Search for city, village, district, or state...',
      fetchError: 'Failed to fetch weather data. Please check your connection.',
      tryAgain: 'Please try searching for another location.',
      humidity: 'Humidity',
      windSpeed: 'Wind Speed',
      pressure: 'Pressure',
      visibility: 'Visibility',
      today: 'Today',
      tomorrow: 'Tomorrow',
      dayAfterTomorrow: 'Day After Tomorrow',
      rainChance: 'Rain',

    },
    budgetPlanner: {
      title: 'Crop Budget & Profit Planner',
      selectCrop: 'Select a Crop to Plan',
      expenditure: 'Expenditure (per Acre)',
      item: 'Item',
      cost: 'Cost (₹)',
      totalExpenditure: 'Total Expenditure',
      estimatedIncome: 'Estimated Income (per Acre)',
      estimatedYield: 'Estimated Yield',
      marketPrice: 'Estimated Market Price',
      totalIncome: 'Total Estimated Income',
      netProfit: 'Estimated Net Profit',
    },
     chatHistory: {
      title: 'Chat History',
      load: 'Load Chat',
      delete: 'Delete',
      newChat: 'New Chat',
      noHistory: 'No conversations yet.',
      deleteConfirm: 'Are you sure you want to delete this conversation?',
      clearAll: 'Clear All',
      clearAllConfirm: 'Clear All History',
      clearAllWarning: 'This will permanently delete all your conversation history. This action cannot be undone.',
      cancel: 'Cancel',
      confirm: 'Confirm',
    },
    toast: {
      voiceEnabled: 'Voice enabled',
      voiceDisabled: 'Voice disabled',
    },
  },
  hi: {
    selectLanguage: ' अपनी भाषा चुनें',
    appTitle: 'कृषि मित्र',
    welcomeMessage: 'नमस्ते! मैं आपकी कैसे मदद कर सकता हूँ?',
    inputPlaceholder: 'एक प्रश्न पूछें या समस्या का वर्णन करें...',
    listening: 'सुन रहा है...',
    error: 'क्षमा करें, कुछ गलत हो गया। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',
    imageUpload: 'छवि अपलोड की गई',
    feedback: 'क्या यह सहायक था?',
    feedbackThanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    header: {
      changeLanguage: 'भाषा बदलें',
      logout: 'लॉग आउट',
      toggleVoiceOn: 'आवाज सक्षम करें',
      toggleVoiceOff: 'आवाज अक्षम करें',
      newChat: 'नई चैट',
      budgetPlanner: 'बजट योजनाकार देखें',
      machinery: 'कृषि मशीनरी देखें',
      cropInsurance: 'फसल बीमा देखें',
      weather: 'मौसम की जानकारी देखें',
      helpline: 'हेल्पलाइन जानकारी देखें',
      cropCalendar: 'फसल कैलेंडर देखें',
      governmentSchemes: 'सरकारी योजनाएं देखें',
      marketPrices: 'बाजार मूल्य देखें',
      alertPreferences: 'चेतावनी प्राथमिकताएं',
    },
    auth: {
      login: 'लॉग इन करें',
      signup: 'साइन अप करें',
      username: 'उपयोगकर्ता नाम',
      password: 'पासवर्ड',
      welcomeBack: 'वापसी पर स्वागत है!',
      createAccount: 'अपना इतिहास सहेजने के लिए एक खाता बनाएँ।',
      loginPrompt: 'पहले से ही एक खाता है?',
      signupPrompt: 'खाता नहीं है?',
      userExists: 'यह उपयोगकर्ता नाम पहले ही लिया जा चुका है।',
      userNotFound: 'उपयोगकर्ता नाम नहीं मिला।',
      invalidCredentials: 'गलत उपयोगकर्ता नाम या पासवर्ड।',
      genericError: 'एक त्रुटि हुई। कृपया पुन: प्रयास करें।',
    },
    marketPrices: {
      title: 'वर्तमान बाजार मूल्य',
      selectRegion: 'क्षेत्र चुनें',
      crop: 'फसल',
      price: 'मूल्य (प्रति क्विंटल)',
      trend: 'प्रवृत्ति',
      regions: {
        north: 'उत्तर',
        south: 'दक्षिण',
        east: 'पूर्व',
        west: 'पश्चिम',
      },
    },
    governmentSchemes: {
      title: 'सरकारी योजनाएं',
      eligibility: 'पात्रता',
      benefits: 'लाभ',
      applicationProcess: 'आवेदन कैसे करें',
    },
    weatherAlerts: {
      title: 'मौसम चेतावनी',
      preferencesTitle: 'चेतावनी प्राथमिकताएं',
      enableAlerts: 'इनके लिए अलर्ट सक्षम करें:',
      heavyRain: 'भारी वर्षा',
      drought: 'सूखा',
      frost: 'पाला',
    },
    cropCalendar: {
      title: 'फसल कैलेंडर',
      selectCrop: 'एक फसल चुनें',
      stage: 'चरण',
      timing: 'समय / महीना',
      filterBySeason: 'मौसम के अनुसार फ़िल्टर करें',
      all: 'सभी',
      kharif: 'खरीफ',
      rabi: 'रबी',
    },
    helpline: {
      title: 'हेल्पलाइन जानकारी',
      nationalHelplines: 'राष्ट्रीय हेल्पलाइन',
      stateAuthorities: 'राज्य कृषि प्राधिकरण',
      nearbyOffices: 'आस-पास के कृषि कार्यालय',
      selectState: 'राज्य चुनें',
      selectDistrict: 'जिला चुनें',
      region: 'क्षेत्र',
      department: 'विभाग',
      contact: 'संपर्क',
    },
    machinery: {
      title: 'कृषि मशीनरी',
      learnMore: ' और जानें',
      cost: 'अनुमानित लागत',
      subsidy: 'सरकारी सब्सिडी',
    },
    cropInsurance: {
      title: 'फसल बीमा योजनाएं',
      coverage: 'कवरेज',
      premium: 'प्रीमियम',
      eligibility: 'पात्रता',
      claimProcess: 'दावा प्रक्रिया',
      documentsRequired: 'आवश्यक दस्तावेज',
      keyBenefits: 'मुख्य लाभ',
      visitWebsite: 'वेबसाइट पर जाएं',
    },
    weatherWidget: {
      title: 'मौसम पूर्वानुमान',
      searchPlaceholder: 'शहर का नाम दर्ज करें...',
      cityNotFound: 'शहर नहीं मिला। कृपया दूसरा शहर आज़माएँ।',
      serviceUnavailable: 'मौसम सेवा वर्तमान में अनुपलब्ध है।',
      fetchError: 'मौसम डेटा लाने में विफल। कृपया अपना कनेक्शन जांचें।',
      feelsLike: 'महसूस होता है',
      humidity: 'नमी',
      windSpeed: 'हवा',
      pressure: 'दबाव',
      visibility: 'दृश्यता',
      sunrise: 'सूर्योदय',
      sunset: 'सूर्यास्त',
    },
    weather: {
      title: 'मौसम रिपोर्ट',
      searchPlaceholder: 'शहर, गाँव, जिला या राज्य का नाम दर्ज करें...',
      fetchError: 'मौसम की जानकारी लाने में असफल। कृपया अपना कनेक्शन जांचें।',
      tryAgain: 'कृपया कोई और स्थान खोजने की कोशिश करें।',
      humidity: 'नमी',
      windSpeed: 'हवा की गति',
      pressure: 'दबाव',
      visibility: 'दृश्यता',
      today: 'आज',
      tomorrow: 'कल',
      dayAfterTomorrow: 'परसों',
      rainChance: 'बारिश',
      recentSearches: 'हाल की खोजें',
      popularLocations: 'लोकप्रिय स्थान',
      threeDayForecast: '3-दिन का मौसम पूर्वानुमान'
    },
    budgetPlanner: {
      title: 'फसल बजट और लाभ योजनाकार',
      selectCrop: 'योजना बनाने के लिए फसल चुनें',
      expenditure: 'व्यय (प्रति एकड़)',
      item: 'मद',
      cost: 'लागत (₹)',
      totalExpenditure: 'कुल व्यय',
      estimatedIncome: 'अनुमानित आय (प्रति एकड़)',
      estimatedYield: 'अनुमानित उपज',
      marketPrice: 'अनुमानित बाजार मूल्य',
      totalIncome: 'कुल अनुमानित आय',
      netProfit: 'अनुमानित शुद्ध लाभ',
    },
     chatHistory: {
      title: 'चैट इतिहास',
      load: 'चैट लोड करें',
      delete: 'हटाएं',
      newChat: 'नई चैट',
      noHistory: 'अभी तक कोई बातचीत नहीं हुई।',
      deleteConfirm: 'क्या आप वाकई इस बातचीत को हटाना चाहते हैं?',
      clearAll: 'सभी साफ करें',
      clearAllConfirm: 'सभी इतिहास साफ करें',
      clearAllWarning: 'यह आपका संपूर्ण बातचीत इतिहास स्थायी रूप से हटा देगा। इस क्रिया को पूर्ववत नहीं किया जा सकता।',
      cancel: 'रद्द करें',
      confirm: 'पुष्टि करें',
    },
    toast: {
      voiceEnabled: 'आवाज सक्षम',
      voiceDisabled: 'आवाज अक्षम',
    },
  },
  ml: {
    selectLanguage: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    appTitle: 'കൃഷി മിത്ര',
    welcomeMessage: 'സ്വാഗതം! ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കും?',
    inputPlaceholder: 'ഒരു ചോദ്യം ചോദിക്കുക അല്ലെങ്കിൽ പ്രശ്നം വിവരിക്കുക...',
    listening: 'ശ്രദ്ധിക്കുന്നു...',
    error: 'ക്ഷമിക്കണം, എന്തോ പിശക് സംഭവിച്ചു. ദയവായി നിങ്ങളുടെ കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    imageUpload: 'ചിത്രം അപ്‌ലോഡ് ചെയ്തു',
    feedback: 'ഇത് സഹായകരമായിരുന്നോ?',
    feedbackThanks: 'നിങ്ങളുടെ അഭിപ്രായത്തിന് നന്ദി!',
    header: {
      changeLanguage: 'ഭാഷ മാറ്റുക',
      logout: 'ലോഗൗട്ട് ചെയ്യുക',
      toggleVoiceOn: 'വോയിസ് പ്രവർത്തനക്ഷമമാക്കുക',
      toggleVoiceOff: 'വോയിസ് പ്രവർത്തനരഹിതമാക്കുക',
      newChat: 'പുതിയ ചാറ്റ്',
      budgetPlanner: 'ബജറ്റ് പ്ലാനർ കാണുക',
      machinery: 'കാർഷിക യന്ത്രങ്ങൾ കാണുക',
      cropInsurance: 'വിള ഇൻഷുർൻസ് കാണുക',
      weather: 'കാലാവസ്ഥാ രിപ്പോർട്ട് കാണുക',
      helpline: 'ഹെൽപ്പ്ലൈൻ വിവരങ്ങൾ കാണുക',
      cropCalendar: 'വിള കലണ്ടർ കാണുക',
      governmentSchemes: 'സർക്കാർ പദ്ധതികൾ കാണുക',
      marketPrices: 'മാർക്കറ്റ് വിലകൾ കാണുക',
      alertPreferences: 'അലേർട്ട് മുൻഗണനകൾ',
    },
    auth: {
      login: 'ലോഗിൻ ചെയ്യുക',
      signup: 'സൈൻ അപ്പ് ചെയ്യുക',
      username: 'ഉപയോക്തൃനാമം',
      password: 'പാസ്‌വേഡ്',
      welcomeBack: 'വീണ്ടും സ്വാഗതം!',
      createAccount: 'നിങ്ങളുടെ ചരിത്രം സംരക്ഷിക്കാൻ ഒരു അക്കൗണ്ട് ഉണ്ടാക്കുക.',
      loginPrompt: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
      signupPrompt: 'അക്കൗണ്ട് ഇല്ലേ?',
      userExists: 'ഈ ഉപയോക്തൃനാമം ഇതിനകം ഉപയോഗത്തിലുണ്ട്.',
      userNotFound: 'ഉപയോക്തൃനാമം കണ്ടെത്താനായില്ല.',
      invalidCredentials: 'തെറ്റായ ഉപയോക്തൃനാമം അല്ലെങ്കിൽ പാസ്‌വേഡ്.',
      genericError: 'ഒരു പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    },
    marketPrices: {
      title: 'നിലവിലെ മാർക്കറ്റ് വിലകൾ',
      selectRegion: 'പ്രദേശം തിരഞ്ഞെടുക്കുക',
      crop: 'വിള',
      price: 'വില (ക്വിന്റലിന്)',
      trend: 'പ്രവണത',
      regions: {
        north: 'വടക്ക്',
        south: 'തെക്ക്',
        east: 'കിഴക്ക്',
        west: 'പടിഞ്ഞാറ്',
      },
    },
    governmentSchemes: {
      title: 'സർക്കാർ പദ്ധതികൾ',
      eligibility: 'യോഗ്യത',
      benefits: 'പ്രയോജനങ്ങൾ',
      applicationProcess: 'അപേക്ഷിക്കേണ്ടവിധം',
    },
    weatherAlerts: {
      title: 'കാലാവസ്ഥാ മുന്നറിയിപ്പ്',
      preferencesTitle: 'അലേർട്ട് മുൻഗണനകൾ',
      enableAlerts: 'ഇവയ്‌ക്കായി അലേർട്ടുകൾ പ്രവർത്തനക്ഷമമാക്കുക:',
      heavyRain: 'കനത്ത മഴ',
      drought: 'വരൾച്ച',
      frost: 'മഞ്ഞ്',
    },
    cropCalendar: {
      title: 'വിള കലണ്ടർ',
      selectCrop: 'ഒരു വിള തിരഞ്ഞെടുക്കുക',
      stage: 'ഘട്ടം',
      timing: 'സമയം / മാസം',
      filterBySeason: 'സീസൺ അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
      all: 'എല്ലാം',
      kharif: 'ഖാരിഫ്',
      rabi: 'റാബി',
    },
     helpline: {
      title: 'ഹെൽപ്പ്ലൈൻ വിവരങ്ങൾ',
      nationalHelplines: 'ദേശീയ ഹെൽപ്പ്ലൈനുകൾ',
      stateAuthorities: 'സംസ്ഥാന കാർഷിക അധികാരികൾ',
      nearbyOffices: 'അടുത്തുള്ള കൃഷി ഓഫീസുകൾ',
      selectState: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
      selectDistrict: 'ജില്ല തിരഞ്ഞെടുക്കുക',
      region: 'പ്രദേശം',
      department: 'വകുപ്പ്',
      contact: 'ബന്ധപ്പെടുക',
    },
    machinery: {
      title: 'കാർഷിക യന്ത്രങ്ങൾ',
      learnMore: 'കൂടുതലറിയുക',
      cost: 'ഏകദേശ വില',
      subsidy: 'സർക്കാർ സബ്‌സിഡി',
    },
    cropInsurance: {
      title: 'വിള ഇൻഷുർൻസ് പദ്ധതികൾ',
      coverage: 'കവറേജ്',
      premium: 'പ്രീമിയം',
      eligibility: 'യോഗ്യത',
      claimProcess: 'ക്ലെയിം പ്രക്രിയ',
      documentsRequired: 'ആവശ്യമായ പ്രമാണങ്ങൾ',
      keyBenefits: 'മുഖ്യ പ്രയോജനങ്ങൾ',
      visitWebsite: 'വെബ്സൈറ്റ് സന്ദർശിക്കുക',
    },
    weatherWidget: {
      title: 'കാലാവസ്ഥാ പ്രവചനം',
      searchPlaceholder: 'നഗരത്തിൻ്റെ പേര് നൽകുക...',
      cityNotFound: 'നഗരം കണ്ടെത്താനായില്ല. ദയവായി മറ്റൊരു നഗരം പരീക്ഷിക്കുക.',
      serviceUnavailable: 'കാലാവസ്ഥാ സേവനം നിലവിൽ ലഭ്യമല്ല.',
      fetchError: 'കാലാവസ്ഥാ ഡാറ്റ ലഭ്യമാക്കുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി നിങ്ങളുടെ കണക്ഷൻ പരിശോധിക്കുക.',
      feelsLike: 'അനുഭവപ്പെടുന്നത്',
      humidity: 'ഈർപ്പം',
      windSpeed: 'കാറ്റ്',
      pressure: 'മർദ്ദം',
      visibility: 'കാഴ്ച',
      sunrise: 'സൂര്യോദയം',
      sunset: 'സൂര്യാസ്തമയം',
    },
    weather: {
      title: 'കാലാവസ്ഥാ റിപ്പോർട്ടുകൾ',
      searchPlaceholder: 'നഗരം, ഗ്രാമം, ജില്ല അല്ലെങ്കിൽ സംസ്ഥാനത്തിന്റെ പേര് നൽകുക...',
      fetchError: 'കാലാവസ്ഥാ ഡാറ്റ ലഭ്യമാക്കുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി നിങ്ങളുടെ കണക്ഷൻ പരിശോധിക്കുക.',
      tryAgain: 'ദയവായി മറ്റൊരു സ്ഥലം തേടാൻ ശ്രമിക്കുക.',
      humidity: 'ഈർപ്പം',
      windSpeed: 'കാറ്റിന്റെ വേഗത',
      pressure: 'മർദ്ദം',
      visibility: 'കാഴ്ച',
      today: 'ഇന്ന്',
      tomorrow: 'നാളെ',
      dayAfterTomorrow: 'നാളെ അനുദിനം',
      rainChance: 'മഴ',
      recentSearches: 'സമീപകാല തിരയലുകൾ',
      popularLocations: 'ജനപ്രിയ സ്ഥലങ്ങൾ',
      threeDayForecast: '3-ദിവസത്തെ കാലാവസ്ഥാ പ്രവചനം'
    },
    budgetPlanner: {
      title: 'വിള ബജറ്റും ലാഭ ആസൂത്രണവും',
      selectCrop: 'ആസൂത്രണം ചെയ്യാൻ ഒരു വിള തിരഞ്ഞെടുക്കുക',
      expenditure: 'ചെലവ് (ഏക്കറിന്)',
      item: 'ഇനം',
      cost: 'ചെലവ് (₹)',
      totalExpenditure: 'ആകെ ചെലവ്',
      estimatedIncome: 'കണക്കാക്കിയ വരുമാനം (ഏക്കറിന്)',
      estimatedYield: 'കണക്കാക്കിയ വിളവ്',
      marketPrice: 'കണക്കാക്കിയ മാർക്കറ്റ് വില',
      totalIncome: 'ആകെ കണക്കാക്കിയ വരുമാനം',
      netProfit: 'കണക്കാക്കിയ അറ്റാദായം',
    },
     chatHistory: {
      title: 'ചാറ്റ് ചരിത്രം',
      load: 'ചാറ്റ് ലോഡ് ചെയ്യുക',
      delete: 'ഇല്ലാതാക്കുക',
      newChat: 'പുതിയ ചാറ്റ്',
      noHistory: 'ഇതുവരെ സംഭാഷണങ്ങളൊന്നുമില്ല.',
      deleteConfirm: 'ഈ സംഭാഷണം ഇല്ലാതാക്കണമെന്ന് ഉrparrാണോ?',
      clearAll: 'എല്ലാം മായ്‌ക്കുക',
      clearAllConfirm: 'എല്ലാ ചരിത്രവും മായ്‌ക്കുക',
      clearAllWarning: 'ഇത് നിങ്ങളുടെ എല്ലാ സംഭാഷണ ചരിത്രവും ശാശ്വതമായി ഇല്ലാതാക്കും. ഈ പ്രവർത്തനം പഴയപടി ചെയ്യാൻ കഴിയില്ല.',
      cancel: 'റദ്ദാക്കുക',
      confirm: 'സ്ഥിരീകരിക്കുക',
    },
    toast: {
      voiceEnabled: 'വോയിസ് പ്രവർത്തനക്ഷമമാക്കി',
      voiceDisabled: 'വോയിസ് പ്രവർത്തനരഹിതമാക്കി',
    },
  },
  te: {
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    appTitle: 'కృషి మిత్ర',
    welcomeMessage: 'స్వాగతం! నేను మీకు ఎలా సహాయపడగలను?',
    inputPlaceholder: 'ఒక ప్రశ్న అడగండి లేదా సమస్యను వివరించండి...',
    listening: 'వినడం జరుగుతోంది...',
    error: 'క్షమించండి, ఏదో పొరపాటు జరిగింది. దయచేసి మీ కనెక్షన్‌ని తనిఖీ చేసి, మళ్లీ ప్రయత్నించండి.',
    imageUpload: 'చిత్రం అప్‌లోడ్ చేయబడింది',
    feedback: 'ఇది సహాయకరంగా ఉందా?',
    feedbackThanks: 'మీ అభిప్రాయానికి ధన్యవాదాలు!',
    header: {
      changeLanguage: 'భాషను మార్చండి',
      logout: 'లాగ్ అవుట్',
      toggleVoiceOn: 'వాయిస్‌ని ప్రారంభించండి',
      toggleVoiceOff: 'వాయిస్‌ని నిలిపివేయండి',
      newChat: 'కొత్త చాట్',
      budgetPlanner: 'బడ్జెట్ ప్లానర్ చూడండి',
      machinery: 'వ్యవసాయ యంత్రాలను చూడండి',
      cropInsurance: 'పంట ఇన్‌షురెన్స్ చూడండి',
      weather: 'వాతావరణ రిపోర్టులు చూడండి',
      helpline: 'హెల్ప్‌లైన్ సమాచారం చూడండి',
      cropCalendar: 'పంట క్యాలెండర్ చూడండి',
      governmentSchemes: 'ప్రభుత్వ పథకాలు చూడండి',
      marketPrices: 'మార్కెట్ ధరలను చూడండి',
      alertPreferences: 'హెచ్చరిక ప్రాధాన్యతలు',
    },
    auth: {
      login: 'లాగిన్',
      signup: 'సైన్ అప్',
      username: 'వినియోగదారు పేరు',
      password: 'పాస్‌వర్డ్',
      welcomeBack: 'తిరిగి స్వాగతం!',
      createAccount: 'మీ చరిత్రను సేవ్ చేయడానికి ఖాతాను సృష్టించండి.',
      loginPrompt: 'ఇప్పటికే ఖాతా ఉందా?',
      signupPrompt: 'ఖాతా లేదా?',
      userExists: 'ఈ వినియోగదారు పేరు ఇప్పటికే వాడుకలో ఉంది.',
      userNotFound: 'వినియోగదారు పేరు కనుగొనబడలేదు.',
      invalidCredentials: 'తప్పు వినియోగదారు పేరు లేదా పాస్‌వర్డ్.',
      genericError: 'ఒక లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    },
    marketPrices: {
      title: 'ప్రస్తుత మార్కెట్ ధరలు',
      selectRegion: 'ప్రాంతాన్ని ఎంచుకోండి',
      crop: 'పంట',
      price: 'ధర (క్వింటాల్‌కు)',
      trend: 'ధోరణి',
      regions: {
        north: 'ఉత్తరం',
        south: 'దక్షిణం',
        east: 'తూర్పు',
        west: 'పడమర',
      },
    },
    governmentSchemes: {
      title: 'ప్రభుత్వ పథకాలు',
      eligibility: 'అర్హత',
      benefits: 'ప్రయోజనాలు',
      applicationProcess: 'ఎలా దరఖాస్తు చేయాలి',
    },
    weatherAlerts: {
      title: 'వాతావరణ హెచ్చరిక',
      preferencesTitle: 'హెచ్చరిక ప్రాధాన్యతలు',
      enableAlerts: 'దీని కోసం హెచ్చరికలను ప్రారంభించండి:',
      heavyRain: 'భారీ వర్షం',
      drought: 'కరువు',
      frost: 'మంచు',
    },
    cropCalendar: {
      title: 'పంట క్యాలెండర్',
      selectCrop: 'పంటను ఎంచుకోండి',
      stage: 'దశ',
      timing: 'సమయం / నెల',
      filterBySeason: 'సీజన్ ప్రకారం ఫిల్టర్ చేయండి',
      all: 'అన్నీ',
      kharif: 'ఖరీఫ్',
      rabi: 'రబీ',
    },
    helpline: {
      title: 'హెల్ప్‌లైన్ సమాచారం',
      nationalHelplines: 'జాతీయ హెల్ప్‌లైన్‌లు',
      stateAuthorities: 'రాష్ట్ర వ్యవసాయ అధికారులు',
      nearbyOffices: 'సమీపంలోని వ్యవసాయ కార్యాలయాలు',
      selectState: 'రాష్ట్రాన్ని ఎంచుకోండి',
      selectDistrict: 'జిల్లాను ఎంచుకోండి',
      region: 'ప్రాంతం',
      department: 'శాఖ',
      contact: 'సంప్రదించండి',
    },
    machinery: {
      title: 'వ్యవసాయ యంత్రాలు',
      learnMore: 'మరింత తెలుసుకోండి',
      cost: 'అంచనా వ్యయం',
      subsidy: 'ప్రభుత్వ సబ్సిడీ',
    },
    cropInsurance: {
      title: 'పంటల ఇన్‌షురెన్స్ పథకాలు',
      coverage: 'కవరేజ్',
      premium: 'ప్రీమియం',
      eligibility: 'అర్హత',
      claimProcess: 'క్లెయిం ప్రక్రియ',
      documentsRequired: 'అవసరమైన పత్రాలు',
      keyBenefits: 'ముఖ్య ప్రయోజనాలు',
      visitWebsite: 'వెబ్‌సైట్‌ను సందర్శించండి',
    },
    weatherWidget: {
      title: 'వాతావరణ సూచన',
      searchPlaceholder: 'నగరం పేరు నమోదు చేయండి...',
      cityNotFound: 'నగరం కనుగొనబడలేదు. దయచేసి మరొక నగరాన్ని ప్రయత్నించండి.',
      serviceUnavailable: 'వాతావరణ సేవ ప్రస్తుతం అందుబాటులో లేదు.',
      fetchError: 'వాతావరణ డేటాను పొందడంలో విఫలమైంది. దయచేసి మీ కనెక్షన్‌ని తనిఖీ చేయండి.',
      feelsLike: 'అనిపిస్తుంది',
      humidity: 'తేమ',
      windSpeed: 'గాలి',
      pressure: 'పీడనం',
      visibility: 'దృశ్యమానత',
      sunrise: 'సూర్యోదయం',
      sunset: 'సూర్యాస్తమయం',
    },
    weather: {
      title: 'వాతావరణ రిపోర్టులు',
      searchPlaceholder: 'నగరం, గ్రామం, జిల్లా లేదా రాష్ట్ర పేరు రాయండి...',
      fetchError: 'వాతావరణ డేటా తేవడంలో విఫలమైంది. దయచేసి మీ కనెక్షన్ తనిఖీ చేసి మళ్ళీ ప్రయత్నించండి.',
      tryAgain: 'దయచేసి మరొ స్థలానికి వెతకడానికి ప్రయత్నించండి.',
      humidity: 'తేమ శాతం',
      windSpeed: 'గాళి వేగం',
      pressure: 'మర్దనం',
      visibility: 'కనుగొనుత',
      today: 'ఈరోజు',
      tomorrow: 'రేపు', 
      dayAfterTomorrow: 'ఎల్లుండి',
      rainChance: 'వర్షం',
      recentSearches: 'ఇక్కడ వెతుకులాటలు',
      popularLocations: 'ప్రాముఖ్య స్థలాలు',
      threeDayForecast: '3-రోజుల వాతావరణ పూర్వానుమానం',

    },
    budgetPlanner: {
      title: 'పంట బడ్జెట్ & లాభాల ప్రణాళిక',
      selectCrop: 'ప్రణాళిక చేయడానికి పంటను ఎంచుకోండి',
      expenditure: 'ఖర్చు (ఎకరానికి)',
      item: 'అంశం',
      cost: 'ఖర్చు (₹)',
      totalExpenditure: 'మొత్తం ఖర్చు',
      estimatedIncome: 'అంచనా ఆదాయం (ఎకరానికి)',
      estimatedYield: 'అంచనా దిగుబడి',
      marketPrice: 'అంచనా మార్కెట్ ధర',
      totalIncome: 'మొత్తం అంచనా ఆదాయం',
      netProfit: 'అంచనా నికర లాభం',
    },
    chatHistory: {
      title: 'చాట్ చరిత్ర',
      load: 'చాట్‌ను లోడ్ చేయండి',
      delete: 'తొలగించు',
      newChat: 'కొత్త చాట్',
      noHistory: 'ఇంకా సంభాషణలు లేవు.',
      deleteConfirm: 'మీరు ఈ సంభాషణను తొలగించాలనుకుంటున్నారని ఖಚితంగా ఉన్నారా?',
      clearAll: 'అన్నీ క్లియర్ చేయండి',
      clearAllConfirm: 'అన్ని చరిత్రను క్లియర్ చేయండి',
      clearAllWarning: 'ఇది మీ మొత్తం సంభాషణ చరిత్రను శాశ్వతంగా తొలగిస్తుంది. ఈ చర్యను రద్దు చేయలేరు.',
      cancel: 'రద్దు చేయి',
      confirm: 'ధృవీకరించు',
    },

  },
};